import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { createRequire } from "node:module";
import test from "node:test";
import sharp from "sharp";

const require = createRequire(import.meta.url);
const { createStorageService, hasAiFilenamePrefix, normalizeImageBaseName } = require("../backend/services/storageService");

test("nomes com prefixo de IA são substituídos pela identidade do cinema", () => {
  assert.equal(normalizeImageBaseName("ChatGPT Image 2026.png"), "cine-cruzeiro-image-2026");
  assert.equal(normalizeImageBaseName("DALL-E_cartaz terror.webp"), "cine-cruzeiro-cartaz-terror");
  assert.equal(normalizeImageBaseName("IA-poster.jpg"), "cine-cruzeiro-poster");
  assert.equal(normalizeImageBaseName("ainda-em-cartaz.jpg"), "ainda-em-cartaz");
  assert.equal(hasAiFilenamePrefix("openai-campanha.png"), true);
  assert.equal(hasAiFilenamePrefix("ainda-em-cartaz.jpg"), false);
});

test("upload remove metadados de origem e grava somente metadados do Cine Cruzeiro", async (t) => {
  const rootDir = await fs.mkdtemp(path.join(os.tmpdir(), "cine-image-sanitize-"));
  t.after(() => fs.rm(rootDir, { recursive: true, force: true }));
  const source = await sharp({ create: { width: 80, height: 120, channels: 3, background: "#17345c" } })
    .jpeg()
    .withExif({ IFD0: { Artist: "ChatGPT", Software: "AI Generator", ImageDescription: "generated by AI" } })
    .withXmp('<x:xmpmeta xmlns:x="adobe:ns:meta/"><old>ChatGPT</old></x:xmpmeta>')
    .toBuffer();
  const storage = createStorageService({ publicDir: rootDir, rootDir });
  const uploaded = await storage.uploadImageBuffer({
    buffer: source,
    filename: "ChatGPT Image promocao.jpg",
    contentType: "image/jpeg",
    folder: "campaigns"
  });

  assert.match(uploaded.url, /\/campaigns\/cine-cruzeiro-image-promocao-/);
  const output = await fs.readFile(uploaded.path);
  const metadata = await sharp(output).metadata();
  const embedded = Buffer.concat([metadata.exif || Buffer.alloc(0), metadata.xmp || Buffer.alloc(0)]).toString("utf8");
  assert.match(embedded, /Cine Cruzeiro/);
  assert.match(embedded, /Cine Cruzeiro Media Pipeline/);
  assert.doesNotMatch(embedded, /ChatGPT|AI Generator|generated by AI/);
});
